### ISSUE TITLE
B&B

### ISSUE THREAD

**Issue by kmsdevnet** [zeitgeist2018/AdminPro-Angular#1]
buenas. buscando la serie de beavis y butthead en castellano acabé en forocoches y justo había posts recientes de más gente buscando lo mismo. leí que decías que la tenías al completo y la estabas subiendo. llevo literalmente años buscándola... por casualidad tienes enlaces para poder descargarla please?

perdona que te haya contactado por aquí, no tengo cuenta en fc. saludos.

**Comment by zeitgeist2018** [comment]
Por favor contáctame por otro medio, no por aquí. 
Gracias

**Comment by kmsdevnet** [comment]
por qúe otro medio? ya el hecho de encontrarte en github fue suerte. como sea, por tu respuesta me da que no tienes nada subido a ninguna parte. no obstante, si me facilitas otro medio por el que pueda perdirte lo que ya te he pedido por aquí... yo encantado. son muchos años detrás de esa serie como para no lucharle un poco al ver que hay oportunidad de conseguirla
